baseURL = 'https://cs.cloudsx.top/'
languageCode = 'zh-cn'
title = '我的考研复习笔记'
theme = 'hugo-book'

disablePathToLower = true
enableGitInfo = true

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[params]
  BookTheme = 'light'
  BookSection = 'math'
  BookSearch = true
  BookKaTeX = true