baseURL = 'https://cs.cloudsx.top/'
languageCode = 'zh-cn'
title = '我的考研复习笔记'
theme = 'hugo-book'

disablePathToLower = true
enableGitInfo = true
timeout = '300s'
buildFuture = true

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[params]
  BookTheme = 'light'
  BookSearch = true
  BookKaTeX = true
  BookSection = '*'

[[menu.home]]
  name = '政治'
  pageRef = '/zz/'
  weight = 1

[[menu.home]]
  name = '英语'
  pageRef = '/english/'
  weight = 2

[[menu.home]]
  name = '数学'
  pageRef = '/math/'
  weight = 3

[[menu.home]]
  name = '计算机'
  pageRef = '/cs/'
  weight = 4

[[menu.home]]
  name = '归档'
  pageRef = '/archives/'
  weight = 5